WIDTH = 960
HEIGHT = 540
WIDTH_DEPTH = 848
HEIGHT_DEPTH = 480

BASKET = "basket"
BALL = "ball"
ORIGINAL_WINDOW = "Original"
MASKED_WINDOW = "Thresh"
MASKED_WINDOW_BASKET = "Basket"
DEPTH_WINDOW = "Depth"
TRACKBAR_WINDOW = "Trackbar"

MINIMAL_BALL_SIZE_TO_DETECT = 7
MIN_BALL_RADIUS = 2
BALL_SIZE_TO_STOP = 85
ROBOT_SPEED = 18

CENTER_OFFSET = 30
CENTER_OFFSET_Y = 20
CROP_Y1 = 170
CROP_Y2 = 350
CENTER_RANGE = range(int(WIDTH / 2) - CENTER_OFFSET, int(WIDTH / 2) + CENTER_OFFSET, 1)
CENTER_X = int(WIDTH / 2)
CENTER_Y = int(CROP_Y2 / 2)
CENTER_RANGE_Y = range(CENTER_Y - CENTER_OFFSET_Y, CENTER_Y + CENTER_OFFSET_Y, 1)
