WIDTH = 960
HEIGHT = 540
WIDTH_DEPTH = 848
HEIGHT_DEPTH = 480

BASKET = "basket"
BALL = "ball"
ORIGINAL_WINDOW = "Original"
MASKED_WINDOW = "Thresh"
MASKED_WINDOW_BASKET = "Basket"
DEPTH_WINDOW = "Depth"
TRACKBAR_WINDOW = "Trackbar"

MINIMAL_BALL_SIZE_TO_DETECT = 7
MIN_BALL_RADIUS = 2
CENTER_OFFSET = 100
CENTER_RANGE = range(int(WIDTH / 2) - CENTER_OFFSET, int(WIDTH / 2) + CENTER_OFFSET, 1)

BALL_SIZE_TO_STOP = 85
ROBOT_SPEED = 18
                
                
