WIDTH = 848
HEIGHT = 480

CENTER_X = int(848 / 2)
CENTER_Y = int(480 / 2) + 250

CENTER_OFFSET_X = 30
CENTER_OFFSET_Y = 30
CENTER_OFFSET_BALL = 15

CENTER_RANGE_X = range(CENTER_X - CENTER_OFFSET_X, CENTER_X + CENTER_OFFSET_X, 1)
CENTER_RANGE_Y = range(CENTER_Y - CENTER_OFFSET_Y, CENTER_Y + CENTER_OFFSET_Y, 1)
CENTER_RANGE_BASKET = range(CENTER_X - CENTER_OFFSET_BALL, CENTER_X + CENTER_OFFSET_BALL, 1)
